spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8
    username: root
    password: root

  main:
    banner-mode: off

  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: error
