spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8
    username: root
    password: root

  main:
    banner-mode: off

  thymeleaf:
    cache: false

  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: error

server:
  port: 443
  ssl.key-store: classpath:keystore.jks
  ssl.key-store-password: 123456
  ssl.key-password: 123456
  ssl.key-alias: tomcat
