spring:
  main:
    banner-mode: off

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flow_study?serverTimezone=GMT%2B8&charset=utf8mb4&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: root

  liquibase:
    enabled: false
